language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

install: true
script: ./mvnw --settings .travis/settings.xml clean verify -P run-its

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - develrulez@gmail.com